apiVersion: v1
kind: Service
metadata:
 name: app-service
 labels:
  app: invemtory-app
spec:
 selector:
   app: inventory-app
 ports:
  - name: http
    protocol: TCP
    targetPort: 8085
 type: LoadBalancer
    
