apiVersion: apps/v1
kind: Deployment
metadata:
 name: my-inventory-app
spec:
 replicas: 3
 selector:
  matchLabels:
   app: inventory-app
 template:
   metadata:
    labels: 
      app: inventory-app
   spec:
    - name: inventory
      image: 398496485913.dkr.ecr.us-east-2.amazonaws.com/inventory:latest
      imagePullPolicy: Always
      ports:
       - name: http
         protocol: TCP
         containerPort: 8085
  
